In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv("../data/ai4i2020_augmented.csv")  
df.head()

,UDI,Product ID,Quality Type,Machine Type,Air temperature [K],Process temperature [K],Rotational speed [rpm],Torque [Nm],Cutting force [N],Tool flank wear VB [mm],Machine failure,TWF,HDF,PWF,OSF,RNF
0,1,M14860,M,Turning,298.1,308.6,1551,42.8,1426.4,0.005,0,0,0,0,0,0
1,2,L47181,L,Milling,298.2,308.7,1408,46.3,2963.7,0.009,0,0,0,0,0,0
2,3,L47182,L,Turning,298.1,308.5,1498,49.4,1620.1,0.011,0,0,0,0,0,0
3,4,L47183,L,Turning,298.2,308.6,1433,39.5,1298.9,0.012,0,0,0,0,0,0
4,5,L47184,L,Milling,298.2,308.7,1408,40.0,2387.7,0.016,0,0,0,0,0,0

In [4]:
print(df.shape)
print(df.columns.tolist())

(10000, 16)
['UDI', 'Product ID', 'Quality Type', 'Machine Type', 'Air temperature [K]', 'Process temperature [K]', 'Rotational speed [rpm]', 'Torque [Nm]', 'Cutting force [N]', 'Tool flank wear VB [mm]', 'Machine failure', 'TWF', 'HDF', 'PWF', 'OSF', 'RNF']

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 16 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   UDI                      10000 non-null  int64
 1   Product ID               10000 non-null  str
 2   Quality Type             10000 non-null  str
 3   Machine Type             10000 non-null  str
 4   Air temperature [K]      10000 non-null  float64
 5   Process temperature [K]  10000 non-null  float64
 6   Rotational speed [rpm]   10000 non-null  int64
 7   Torque [Nm]              10000 non-null  float64
 8   Cutting force [N]        10000 non-null  float64
 9   Tool flank wear VB [mm]  10000 non-null  float64
 10  Machine failure          10000 non-null  int64
 11  TWF                      10000 non-null  int64
 12  HDF                      10000 non-null  int64
 13  PWF                      10000 non-null  int64
 14  OSF                      10000 non-null  int64
 15  RNF                      10000 non-null  int64
dtypes: float64(5), int64(8), str(3)
memory usage: 1.4 MB

In [6]:
df.isnull().sum()

UDI                        0
Product ID                 0
Quality Type               0
Machine Type               0
Air temperature [K]        0
Process temperature [K]    0
Rotational speed [rpm]     0
Torque [Nm]                0
Cutting force [N]          0
Tool flank wear VB [mm]    0
Machine failure            0
TWF                        0
HDF                        0
PWF                        0
OSF                        0
RNF                        0
dtype: int64

In [7]:
df.describe()

,UDI,Air temperature [K],Process temperature [K],Rotational speed [rpm],Torque [Nm],Cutting force [N],Tool flank wear VB [mm],Machine failure,TWF,HDF,PWF,OSF,RNF
count,10000.00000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.00000
mean,5000.50000,300.004930,310.005560,1538.776100,39.986910,2249.897850,0.149012,0.035500,0.004600,0.011500,0.009500,0.009800,0.00190
std,2886.89568,2.000259,1.483734,179.284096,9.968934,875.347022,0.093084,0.185049,0.067671,0.106625,0.097009,0.098514,0.04355
min,1.00000,295.300000,305.700000,1168.000000,3.800000,224.200000,0.005000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000
25%,2500.75000,298.300000,308.800000,1423.000000,33.200000,1534.875000,0.068000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000
50%,5000.50000,300.100000,310.100000,1503.000000,40.100000,2149.050000,0.141000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000
75%,7500.25000,301.500000,311.100000,1612.000000,46.800000,2902.800000,0.225000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000
max,10000.00000,304.500000,313.800000,2886.000000,76.600000,5725.600000,0.434000,1.000000,1.000000,1.000000,1.000000,1.000000,1.00000

In [8]:
df["Machine failure"].value_counts()

Machine failure
0    9645
1     355
Name: count, dtype: int64

In [9]:
df[["Cutting force [N]", "Tool flank wear VB [mm]"]].describe()

       Cutting force [N]  Tool flank wear VB [mm]
count       10000.000000             10000.000000
mean         2249.897850                 0.149012
std           875.347022                 0.093084
min           224.200000                 0.005000
25%          1534.875000                 0.068000
50%          2149.050000                 0.141000
75%          2902.800000                 0.225000
max          5725.600000                 0.434000